/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.onboarding.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * DevicesReq
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-21T12:54:04.779Z")
public class DevicesReq {
  @SerializedName("device_holder_name")
  private String deviceHolderName = null;

  @SerializedName("device_holder_role")
  private String deviceHolderRole = null;

  public DevicesReq deviceHolderName(String deviceHolderName) {
    this.deviceHolderName = deviceHolderName;
    return this;
  }

   /**
   * Get deviceHolderName
   * @return deviceHolderName
  **/
   @Schema(description = "")
  public String getDeviceHolderName() {
    return deviceHolderName;
  }

  public void setDeviceHolderName(String deviceHolderName) {
    this.deviceHolderName = deviceHolderName;
  }

  public DevicesReq deviceHolderRole(String deviceHolderRole) {
    this.deviceHolderRole = deviceHolderRole;
    return this;
  }

   /**
   * Get deviceHolderRole
   * @return deviceHolderRole
  **/
   @Schema(description = "")
  public String getDeviceHolderRole() {
    return deviceHolderRole;
  }

  public void setDeviceHolderRole(String deviceHolderRole) {
    this.deviceHolderRole = deviceHolderRole;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DevicesReq devicesReq = (DevicesReq) o;
    return Objects.equals(this.deviceHolderName, devicesReq.deviceHolderName) &&
        Objects.equals(this.deviceHolderRole, devicesReq.deviceHolderRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceHolderName, deviceHolderRole);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DevicesReq {\n");
    
    sb.append("    deviceHolderName: ").append(toIndentedString(deviceHolderName)).append("\n");
    sb.append("    deviceHolderRole: ").append(toIndentedString(deviceHolderRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

