/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.onboarding.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.IOException;

/**
 * ImageBody
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-21T12:54:04.779Z")
public class ImageBody {
  @SerializedName("big_image")
  private String bigImage = null;

  @SerializedName("small_image")
  private String smallImage = null;

  @SerializedName("mer_id")
  private String merId = null;

  public ImageBody bigImage(String bigImage) {
    this.bigImage = bigImage;
    return this;
  }

   /**
   * Get bigImage
   * @return bigImage
  **/
   @Schema(description = "")
  public String getBigImage() {
    return bigImage;
  }

  public void setBigImage(String bigImage) {
    this.bigImage = bigImage;
  }

  public ImageBody smallImage(String smallImage) {
    this.smallImage = smallImage;
    return this;
  }

   /**
   * Get smallImage
   * @return smallImage
  **/
   @Schema(description = "")
  public String getSmallImage() {
    return smallImage;
  }

  public void setSmallImage(String smallImage) {
    this.smallImage = smallImage;
  }

  public ImageBody merId(String merId) {
    this.merId = merId;
    return this;
  }

   /**
   * Get merId
   * @return merId
  **/
   @Schema(description = "")
  public String getMerId() {
    return merId;
  }

  public void setMerId(String merId) {
    this.merId = merId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageBody imageBody = (ImageBody) o;
    return Objects.equals(this.bigImage, imageBody.bigImage) &&
        Objects.equals(this.smallImage, imageBody.smallImage) &&
        Objects.equals(this.merId, imageBody.merId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bigImage, smallImage, merId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageBody {\n");
    
    sb.append("    bigImage: ").append(toIndentedString(bigImage)).append("\n");
    sb.append("    smallImage: ").append(toIndentedString(smallImage)).append("\n");
    sb.append("    merId: ").append(toIndentedString(merId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

