/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.onboarding.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-21T12:54:04.779Z")
public class InlineResponse200 {
  @SerializedName("merchant_id")
  private String merchantId = null;

  @SerializedName("registered_devices")
  private List<RegisteredDevice> registeredDevices = null;

  @SerializedName("sessiontoken")
  private String sessiontoken = null;

  @SerializedName("status_code")
  private String statusCode = null;

  @SerializedName("status_message")
  private String statusMessage = null;

  public InlineResponse200 merchantId(String merchantId) {
    this.merchantId = merchantId;
    return this;
  }

   /**
   * Get merchantId
   * @return merchantId
  **/
@Schema(description = "")
  public String getMerchantId() {
    return merchantId;
  }

  public void setMerchantId(String merchantId) {
    this.merchantId = merchantId;
  }

  public InlineResponse200 registeredDevices(List<RegisteredDevice> registeredDevices) {
    this.registeredDevices = registeredDevices;
    return this;
  }

  public InlineResponse200 addRegisteredDevicesItem(RegisteredDevice registeredDevicesItem) {
    if (this.registeredDevices == null) {
      this.registeredDevices = new ArrayList<RegisteredDevice>();
    }
    this.registeredDevices.add(registeredDevicesItem);
    return this;
  }

   /**
   * Get registeredDevices
   * @return registeredDevices
  **/
@Schema(description = "")
  public List<RegisteredDevice> getRegisteredDevices() {
    return registeredDevices;
  }

  public void setRegisteredDevices(List<RegisteredDevice> registeredDevices) {
    this.registeredDevices = registeredDevices;
  }

  public InlineResponse200 sessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
    return this;
  }

   /**
   * Get sessiontoken
   * @return sessiontoken
  **/
@Schema(description = "")
  public String getSessiontoken() {
    return sessiontoken;
  }

  public void setSessiontoken(String sessiontoken) {
    this.sessiontoken = sessiontoken;
  }

  public InlineResponse200 statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
@Schema(description = "")
  public String getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public InlineResponse200 statusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
    return this;
  }

   /**
   * Get statusMessage
   * @return statusMessage
  **/
@Schema(description = "")
  public String getStatusMessage() {
    return statusMessage;
  }

  public void setStatusMessage(String statusMessage) {
    this.statusMessage = statusMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.merchantId, inlineResponse200.merchantId) &&
        Objects.equals(this.registeredDevices, inlineResponse200.registeredDevices) &&
        Objects.equals(this.sessiontoken, inlineResponse200.sessiontoken) &&
        Objects.equals(this.statusCode, inlineResponse200.statusCode) &&
        Objects.equals(this.statusMessage, inlineResponse200.statusMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merchantId, registeredDevices, sessiontoken, statusCode, statusMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    merchantId: ").append(toIndentedString(merchantId)).append("\n");
    sb.append("    registeredDevices: ").append(toIndentedString(registeredDevices)).append("\n");
    sb.append("    sessiontoken: ").append(toIndentedString(sessiontoken)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusMessage: ").append(toIndentedString(statusMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

