/*
 * Corals app
 * Corals openAPI file
 *
 * OpenAPI spec version: 0.0.10
 * Contact: gp2wins-corals@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package life.corals.onboarding.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RedemptionList
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-01-21T12:54:04.779Z")
public class RedemptionList {
  @SerializedName("mer_cb_redeem_id")
  private String merCbRedeemId = null;

  @SerializedName("redeem_activedays")
  private String redeemActivedays = null;

  @SerializedName("redeem_activedt")
  private String redeemActivedt = null;

  @SerializedName("redeem_acttime")
  private String redeemActtime = null;

  @SerializedName("redeem_deposit_amt")
  private String redeemDepositAmt = null;

  @SerializedName("redeem_description")
  private String redeemDescription = null;

  @SerializedName("redeem_endtime")
  private String redeemEndtime = null;

  @SerializedName("redeem_expdt")
  private String redeemExpdt = null;

  @SerializedName("redeem_grps")
  private List<RedeemGrp> redeemGrps = null;

  @SerializedName("redeem_points")
  private String redeemPoints = null;

  @SerializedName("redeem_title")
  private String redeemTitle = null;

  @SerializedName("redeem_type")
  private String redeemType = null;

  public RedemptionList merCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
    return this;
  }

   /**
   * Get merCbRedeemId
   * @return merCbRedeemId
  **/
@Schema(description = "")
  public String getMerCbRedeemId() {
    return merCbRedeemId;
  }

  public void setMerCbRedeemId(String merCbRedeemId) {
    this.merCbRedeemId = merCbRedeemId;
  }

  public RedemptionList redeemActivedays(String redeemActivedays) {
    this.redeemActivedays = redeemActivedays;
    return this;
  }

   /**
   * Get redeemActivedays
   * @return redeemActivedays
  **/
@Schema(description = "")
  public String getRedeemActivedays() {
    return redeemActivedays;
  }

  public void setRedeemActivedays(String redeemActivedays) {
    this.redeemActivedays = redeemActivedays;
  }

  public RedemptionList redeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
    return this;
  }

   /**
   * Get redeemActivedt
   * @return redeemActivedt
  **/
@Schema(description = "")
  public String getRedeemActivedt() {
    return redeemActivedt;
  }

  public void setRedeemActivedt(String redeemActivedt) {
    this.redeemActivedt = redeemActivedt;
  }

  public RedemptionList redeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
    return this;
  }

   /**
   * Get redeemActtime
   * @return redeemActtime
  **/
@Schema(description = "")
  public String getRedeemActtime() {
    return redeemActtime;
  }

  public void setRedeemActtime(String redeemActtime) {
    this.redeemActtime = redeemActtime;
  }

  public RedemptionList redeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
    return this;
  }

   /**
   * Get redeemDepositAmt
   * @return redeemDepositAmt
  **/
@Schema(description = "")
  public String getRedeemDepositAmt() {
    return redeemDepositAmt;
  }

  public void setRedeemDepositAmt(String redeemDepositAmt) {
    this.redeemDepositAmt = redeemDepositAmt;
  }

  public RedemptionList redeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
    return this;
  }

   /**
   * Get redeemDescription
   * @return redeemDescription
  **/
@Schema(description = "")
  public String getRedeemDescription() {
    return redeemDescription;
  }

  public void setRedeemDescription(String redeemDescription) {
    this.redeemDescription = redeemDescription;
  }

  public RedemptionList redeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
    return this;
  }

   /**
   * Get redeemEndtime
   * @return redeemEndtime
  **/
@Schema(description = "")
  public String getRedeemEndtime() {
    return redeemEndtime;
  }

  public void setRedeemEndtime(String redeemEndtime) {
    this.redeemEndtime = redeemEndtime;
  }

  public RedemptionList redeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
    return this;
  }

   /**
   * Get redeemExpdt
   * @return redeemExpdt
  **/
@Schema(description = "")
  public String getRedeemExpdt() {
    return redeemExpdt;
  }

  public void setRedeemExpdt(String redeemExpdt) {
    this.redeemExpdt = redeemExpdt;
  }

  public RedemptionList redeemGrps(List<RedeemGrp> redeemGrps) {
    this.redeemGrps = redeemGrps;
    return this;
  }

  public RedemptionList addRedeemGrpsItem(RedeemGrp redeemGrpsItem) {
    if (this.redeemGrps == null) {
      this.redeemGrps = new ArrayList<RedeemGrp>();
    }
    this.redeemGrps.add(redeemGrpsItem);
    return this;
  }

   /**
   * Get redeemGrps
   * @return redeemGrps
  **/
@Schema(description = "")
  public List<RedeemGrp> getRedeemGrps() {
    return redeemGrps;
  }

  public void setRedeemGrps(List<RedeemGrp> redeemGrps) {
    this.redeemGrps = redeemGrps;
  }

  public RedemptionList redeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
    return this;
  }

   /**
   * Get redeemPoints
   * @return redeemPoints
  **/
@Schema(description = "")
  public String getRedeemPoints() {
    return redeemPoints;
  }

  public void setRedeemPoints(String redeemPoints) {
    this.redeemPoints = redeemPoints;
  }

  public RedemptionList redeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
    return this;
  }

   /**
   * Get redeemTitle
   * @return redeemTitle
  **/
@Schema(description = "")
  public String getRedeemTitle() {
    return redeemTitle;
  }

  public void setRedeemTitle(String redeemTitle) {
    this.redeemTitle = redeemTitle;
  }

  public RedemptionList redeemType(String redeemType) {
    this.redeemType = redeemType;
    return this;
  }

   /**
   * Get redeemType
   * @return redeemType
  **/
@Schema(description = "")
  public String getRedeemType() {
    return redeemType;
  }

  public void setRedeemType(String redeemType) {
    this.redeemType = redeemType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RedemptionList redemptionList = (RedemptionList) o;
    return Objects.equals(this.merCbRedeemId, redemptionList.merCbRedeemId) &&
        Objects.equals(this.redeemActivedays, redemptionList.redeemActivedays) &&
        Objects.equals(this.redeemActivedt, redemptionList.redeemActivedt) &&
        Objects.equals(this.redeemActtime, redemptionList.redeemActtime) &&
        Objects.equals(this.redeemDepositAmt, redemptionList.redeemDepositAmt) &&
        Objects.equals(this.redeemDescription, redemptionList.redeemDescription) &&
        Objects.equals(this.redeemEndtime, redemptionList.redeemEndtime) &&
        Objects.equals(this.redeemExpdt, redemptionList.redeemExpdt) &&
        Objects.equals(this.redeemGrps, redemptionList.redeemGrps) &&
        Objects.equals(this.redeemPoints, redemptionList.redeemPoints) &&
        Objects.equals(this.redeemTitle, redemptionList.redeemTitle) &&
        Objects.equals(this.redeemType, redemptionList.redeemType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(merCbRedeemId, redeemActivedays, redeemActivedt, redeemActtime, redeemDepositAmt, redeemDescription, redeemEndtime, redeemExpdt, redeemGrps, redeemPoints, redeemTitle, redeemType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RedemptionList {\n");
    
    sb.append("    merCbRedeemId: ").append(toIndentedString(merCbRedeemId)).append("\n");
    sb.append("    redeemActivedays: ").append(toIndentedString(redeemActivedays)).append("\n");
    sb.append("    redeemActivedt: ").append(toIndentedString(redeemActivedt)).append("\n");
    sb.append("    redeemActtime: ").append(toIndentedString(redeemActtime)).append("\n");
    sb.append("    redeemDepositAmt: ").append(toIndentedString(redeemDepositAmt)).append("\n");
    sb.append("    redeemDescription: ").append(toIndentedString(redeemDescription)).append("\n");
    sb.append("    redeemEndtime: ").append(toIndentedString(redeemEndtime)).append("\n");
    sb.append("    redeemExpdt: ").append(toIndentedString(redeemExpdt)).append("\n");
    sb.append("    redeemGrps: ").append(toIndentedString(redeemGrps)).append("\n");
    sb.append("    redeemPoints: ").append(toIndentedString(redeemPoints)).append("\n");
    sb.append("    redeemTitle: ").append(toIndentedString(redeemTitle)).append("\n");
    sb.append("    redeemType: ").append(toIndentedString(redeemType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

